In [1]:
import numpy as np

In [3]:
R1 = np.array([
    [1.0, 1.0, 0.1, 0.4],
    [0.0, 1.0, 0.7, 0.4],
    [0.5, 0.5, 1.0, 0.0],
    [0.5, 0.5, 1.0, 1.0]
])

R2 = np.array([
    [1.0, 0.0, 0.3, 0.2],
    [1.0, 1.0, 0.8, 0.6],
    [0.5, 0.5, 1.0, 1.0],
    [0.5, 0.5, 0.0, 1.0]
])

R3 = np.array([
    [1.0, 0.2, 0.7, 1.0],
    [0.5, 1.0, 1.0, 0.3],
    [0.5, 0.0, 1.0, 0.7],
    [0.0, 0.5, 0.5, 1.0]
])

R4 = np.array([
    [1.0, 0.2, 0.3, 0.0],
    [0.5, 1.0, 0.0, 0.7],
    [0.5, 1.0, 1.0, 0.8],
    [1.0, 0.5, 0.5, 1.0]
])

R5 = np.array([
    [1.0, 0.2, 1.0, 0.9],
    [0.5, 1.0, 0.8, 1.0],
    [0.0, 0.5, 1.0, 0.5],
    [0.5, 0.0, 0.5, 1.0]
])

E = np.array([
    [1.0, 0.1, 0.3, 0.1, 0.9],
    [0.4, 1.0, 0.2, 0.2, 0.7],
    [0.2, 0.5, 1.0, 0.2, 0.1],
    [0.8, 0.3, 0.6, 1.0, 0.3],
    [0.5, 0.2, 0.4, 0.6, 1.0]
])

In [40]:
# н о с п
R1s = np.maximum(R1-R1.T,0)
R2s = np.maximum(R2-R2.T,0)
R3s = np.maximum(R3-R3.T,0)
R4s = np.maximum(R4-R4.T,0)
R5s = np.maximum(R5-R5.T,0)
B = np.array([1-np.max(R1s,axis=0),
              1-np.max(R2s,axis=0),1-np.max(R3s,axis=0),1-np.max(R4s,axis=0),1-np.max(R5s,axis=0)])
print(f'R1s\n{R1s}\nmax\n{np.max(R1s,axis=0)}\nmu_нд_R1\n{B[0]}\n\nR2s\n{R2s}\nmax\n{np.max(R2s,axis=0)}\nmu_нд_R2\n{B[1]}\n\nR3s\n{R3s}\nmax\n{np.max(R3s,axis=0)}\nmu_нд_R3\n{B[2]}\n\nR4s\n{R4s}\nmax\n{np.max(R4s,axis=0)}\nmu_нд_R4\n{B[3]}\n\nR5s\n{R5s}\nmax\n{np.max(R5s,axis=0)}\nmu_нд_R5\n{B[4]}\n\nB\n{B}')

R1s
[[0.  1.  0.  0. ]
 [0.  0.  0.2 0. ]
 [0.4 0.  0.  0. ]
 [0.1 0.1 1.  0. ]]
max
[0.4 1.  1.  0. ]
mu_нд_R1
[0.6 0.  0.  1. ]

R2s
[[0.  0.  0.  0. ]
 [1.  0.  0.3 0.1]
 [0.2 0.  0.  1. ]
 [0.3 0.  0.  0. ]]
max
[1.  0.  0.3 1. ]
mu_нд_R2
[0.  1.  0.7 0. ]

R3s
[[0.  0.  0.2 1. ]
 [0.3 0.  1.  0. ]
 [0.  0.  0.  0.2]
 [0.  0.2 0.  0. ]]
max
[0.3 0.2 1.  1. ]
mu_нд_R3
[0.7 0.8 0.  0. ]

R4s
[[0.  0.  0.  0. ]
 [0.3 0.  0.  0.2]
 [0.2 1.  0.  0.3]
 [1.  0.  0.  0. ]]
max
[1.  1.  0.  0.3]
mu_нд_R4
[0.  0.  1.  0.7]

R5s
[[0.  0.  1.  0.4]
 [0.3 0.  0.3 1. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]]
max
[0.3 0.  1.  1. ]
mu_нд_R5
[0.7 1.  0.  0. ]

B
[[0.6 0.  0.  1. ]
 [0.  1.  0.7 0. ]
 [0.7 0.8 0.  0. ]
 [0.  0.  1.  0.7]
 [0.7 1.  0.  0. ]]


In [104]:
EB = np.array([[max(min(E[i][k], B[k][j]) for k in range(len(E[0]))) for j in range(len(B[0]))] for i in range(len(E))])
C = np.array([[max(min(B.T[i][k], EB[k][j]) for k in range(len(B.T[0]))) for j in range(len(EB[0]))] for i in range(len(B.T))])

print(f'E*B\n{EB}\n\nC\n{C}')

E*B
[[0.7 0.9 0.1 1. ]
 [0.7 1.  0.7 0.4]
 [0.7 0.8 0.5 0.2]
 [0.6 0.6 1.  0.8]
 [0.7 1.  0.6 0.6]]

C
[[0.7 0.7 0.6 0.6]
 [0.7 1.  0.7 0.6]
 [0.7 0.7 1.  0.8]
 [0.7 0.9 0.7 1. ]]


In [134]:
mu_нд_C = 1-np.max(np.maximum(C-C.T,0),axis=0)
cjj = [C[j,j] for j in range(C.shape[0])]
print(f'Cs\n{np.maximum(C-C.T,0)}\nmax\n{np.max(np.maximum(C-C.T,0),axis=0)}\n\nmu_нд_C\n{mu_нд_C}\ncjj\n{cjj}')

Cs
[[0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.1 0.  0.  0.1]
 [0.1 0.3 0.  0. ]]
max
[0.1 0.3 0.  0.1]

mu_нд_C
[0.9 0.7 1.  0.9]
cjj
[0.7, 1.0, 1.0, 1.0]


In [138]:
print(f'mu_нд\n{np.minimum(cjj,mu_нд_C)}')

mu_нд
[0.7 0.7 1.  0.9]


In [142]:
x = np.argmax(np.minimum(cjj,mu_нд_C))
print(f'оптимальная альтернатива x{x+1}, mu_нд(x{x+1}) = {np.minimum(cjj,mu_нд_C)[x]}')

оптимальная альтернатива x3, mu_нд(x3) = 1.0
