In [2]:
import numpy as np

In [19]:
R1 = [
    [1, 1, 0.3, 0.3],
    [0, 1, 0.9, 0.4],
    [0.5, 0.5, 1, 0],
    [0.5, 0.5, 1, 1]
]

R2 = [
    [1, 0, 0.2, 0.5],
    [1, 1, 0.1, 0.4],
    [0.5, 0.5, 1, 1],
    [0.5, 0.5, 0, 1]
]

R3 = [
    [1, 0.1, 0.2, 1],
    [0.5, 1, 1, 0.2],
    [0.5, 0, 1, 0.6],
    [0, 0.5, 0.5, 1]
]

R4 = [
    [1, 0.1, 0.8, 0],
    [0.5, 1, 0, 0.4],
    [0.5, 1, 1, 0.1],
    [1, 0.5, 0.5, 1]
]

R5 = [
    [1, 0.3, 1, 0.9],
    [0.5, 1, 0.4, 1],
    [0, 0.5, 1, 0.9],
    [0.5, 0, 0.5, 1]
]

l1 = 0.3
l2 = 0.2
l3 = 0.1
l4 = 0.1
l5 = 0.3

ls = np.array([l1,l2,l3,l4,l5])
Rs = np.array([R1,R2,R3,R4,R5])

In [22]:
Q1 = np.minimum.reduce([R1,R2,R3,R4,R5])
Q1

array([[1. , 0. , 0.2, 0. ],
       [0. , 1. , 0. , 0.2],
       [0. , 0. , 1. , 0. ],
       [0. , 0. , 0. , 1. ]])

In [5]:
Q1s = np.maximum(Q1-Q1.T,0)
print(f'Q1s\n{Q1s}\n\nmax\n{np.max(Q1s,axis=0)}\n\nm_нд_Q1s\n{1-np.max(Q1s,axis=0)}')

Q1s
[[0.  0.  0.2 0. ]
 [0.  0.  0.  0.2]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]]

max
[0.  0.  0.2 0.2]

m_нд_Q1s
[1.  1.  0.8 0.8]


In [6]:
Q2 = np.einsum('i,ijk->jk', ls, Rs)
Q2

array([[1.  , 0.41, 0.53, 0.56],
       [0.45, 1.  , 0.51, 0.56],
       [0.35, 0.5 , 1.  , 0.54],
       [0.5 , 0.35, 0.55, 1.  ]])

In [7]:
Q2s = np.maximum(Q2-Q2.T,0)
print(f'Q2s\n{Q2s}\n\nmax\n{np.max(Q2s,axis=0)}\n\nm_нд_Q2s\n{1-np.max(Q2s,axis=0)}')

Q2s
[[0.   0.   0.18 0.06]
 [0.04 0.   0.01 0.21]
 [0.   0.   0.   0.  ]
 [0.   0.   0.01 0.  ]]

max
[0.04 0.   0.18 0.21]

m_нд_Q2s
[0.96 1.   0.82 0.79]


In [8]:
print(f'm_нд_Q1 {1-np.max(Q1s,axis=0)}\nm_нд_Q2 {1-np.max(Q2s,axis=0)}\nm_нд {np.minimum(1-np.max(Q1s,axis=0),1-np.max(Q2s,axis=0))}')

m_нд_Q1 [1.  1.  0.8 0.8]
m_нд_Q2 [0.96 1.   0.82 0.79]
m_нд [0.96 1.   0.8  0.79]


In [9]:
print(f'Оптимальная альтернатива - {1+np.argmax(np.minimum(1-np.max(Q1s,axis=0),1-np.max(Q2s,axis=0)))}, = {np.max(np.minimum(1-np.max(Q1s,axis=0),1-np.max(Q2s,axis=0)))}')

Оптимальная альтернатива - 2, = 1.0
